### ISSUE TITLE
How can I create a Mysql-cluster with kubernetes http API?

### ISSUE THREAD

**Issue by lindao99** [oracle/mysql-operator#161]
How can I create a Mysql-cluster with kubernetes http API?
like this way:
```
curl -X POST -H 'Content-Type: application/yaml' --data '
apiVersion: v1
kind: Secret
metadata:
  name: democluster-sec
data:
  username: a3A=
  password: a3AxMjM0NTY=
' http://127.0.0.1:8080/api/v1/namespaces/mgr/secrets
```
Thanks!
