### ISSUE TITLE
container "mysql-agent" in pod "mysql-test-cluster-0" is waiting to start: image can't be pulled

### ISSUE THREAD

**Issue by HenryXie1** [oracle/mysql-operator#237]
## Is this a BUG REPORT or FEATURE REQUEST?

It is an issue when I tested the operator. Not sure if it is a bug

## Versions

**MySQL Operator Version**:
helm list:
mysql-operator          1               Fri Nov 16 03:38:38 2018        DEPLOYED        mysql-operator-0.2.1                    

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5+2.0.2.el7", GitCommit:"03e76fbbae7a955458f4a42fa9b22d6bb7402eb6", GitTreeState:"archive", BuildDate:"2018-07-19T17:01:40Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5+2.0.2.el7", GitCommit:"03e76fbbae7a955458f4a42fa9b22d6bb7402eb6", GitTreeState:"archive", BuildDate:"2018-07-19T17:01:40Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
OCI VM standard2.1

- **OS** (e.g. from /etc/os-release):NAME="Oracle Linux Server"
VERSION="7.5"
ID="ol"
VERSION_ID="7.5"
PRETTY_NAME="Oracle Linux Server 7.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.5

- **Kernel** (e.g. `uname -a`):
Linux instance-cas-mt2 4.1.12-124.18.1.el7uek.x86_64 #2 SMP Tue Aug 7 16:34:48 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
I created mysql-operator via the tutorial in github 
helm install --name mysql-operator mysql-operator
mysql-operator pod is up and running well.

however the mysql pod can't be started due to this error on mysql-agent

Error from server (BadRequest): container "mysql-agent" in pod "mysql-test-cluster-0" is waiting to start: image can't be pulled

However mysql image itself is pulled well

## What you expected to happen?
expect mysql-agent image can be pulled well

##  How to reproduce it (as minimally and precisely as possible)?

helm install --name mysql-operator mysql-operator
apply rbac.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mysql-agent
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-agent
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: default
```
apply simple_cluster.yaml
```
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql-test-cluster
spec:
  members: 2
```
