### ISSUE TITLE
operator don't apply resources

### ISSUE THREAD

**Issue by delgod** [oracle/mysql-operator#248]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**MySQL Operator Version**:  0.3.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): `version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**:
```
gcloud container clusters create --zone us-central1-a mykola-test2 --cluster-version 1.11 --machine-type n1-standard-4 --preemptible --num-nodes=3
```
- **OS** (e.g. from /etc/os-release): GKE default
- **Kernel** (e.g. `uname -a`): GKE default
- **Others**:

## What happened?
operator don't apply resources.
```
$ kubectl get sts/my-mmm -o yaml | grep resources
        resources: {}
        resources: {}
``` 

## What you expected to happen?
resorces section should be applied to StatefulSet

## How to reproduce it (as minimally and precisely as possible)?
apply config with resources below
```
kubectl config set-context $(kubectl config current-context) --namespace=my-namespace
cat <<EOF | kubectl apply -f -
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: my-mmm
spec:
  multiMaster: false
  members: 5
  sslSecret:
    name: mysql-ssl-secret
  resources:
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 1
      memory: 1G
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
EOF
```

## Anything else we need to know?
no

**Comment by DesmondHoLLM** [comment]
I think you need to add the server block as well:

```
resources:
  server:
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 1
      memory: 1G
```

**Comment by delgod** [comment]
@DesmondHoLLM no success, I have run the following command
```
kubectl config set-context $(kubectl config current-context) --namespace=my-namespace
cat <<EOF | kubectl apply -f -
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: my-mmm
spec:
  multiMaster: true
  members: 3
  sslSecret:
    name: mysql-ssl-secret
  resources:
    server:
      limits:
        cpu: 1
        memory: 1G
      requests:
        cpu: 1
        memory: 1G
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
EOF
```
checked with following command
```
$ kubectl get sts/my-mmm -o yaml | grep  resources
        resources: {}
        resources: {}
```

**Comment by DesmondHoLLM** [comment]
@delgod  I think you missed an `i` in memory

```
kubectl config set-context $(kubectl config current-context) --namespace=my-namespace
cat <<EOF | kubectl apply -f -
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: my-mmm
spec:
  multiMaster: true
  members: 3
  resources:
    server:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
EOF
```
