### ISSUE TITLE
Allow setting TZ environment variable

### ISSUE THREAD

**Issue by michaelfig** [oracle/mysql-operator#268]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

I would like to have a `Cluster` resource option for setting the mysql daemon's `TZ` environment variable.  Such as:

```yaml
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql
spec:
  timezone: America/New_York
```

This is useful for supporting specifying the default timezone without running into bootstrap issues, if say, the `default-timezone` setting is used in `my.cnf` (which causes mysqld to fail to start before the `mysql_tzinfo_to_sql` has run).

Thanks,
Michael.
