### ISSUE TITLE
How to set resources to mysql pods ?

### ISSUE THREAD

**Issue by bluemixgarage** [oracle/mysql-operator#277]
I would like to set the `resources` to the pods of the ReplicaSet. Anyone know how to achieve this ?
Cheers.

**Comment by petershaw** [comment]
Like other issues (https://github.com/oracle/mysql-operator/pull/227) shown this should be handled by: 
```
spec:
  resources:
    agent:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    server:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi    
```

But I don't have any luck. The pod still has no resources. 
I am on the current master branch. 

Any Ideas?
