### ISSUE TITLE
Allow to set custom server_id base for clusters 

### ISSUE THREAD

**Issue by gites** [oracle/mysql-operator#69]
## FEATURE REQUEST?

**Description:**
Please add an option to MySQLCluster spec definition that will allow changing default "base" server id. Currently, all cluster will have the same sets of servers ids (1000,1001,1002...) as the base value is hardcoded here: https://github.com/oracle/mysql-operator/blob/master/pkg/resources/statefulsets/statefulset.go#L164 
This option would allow setting different server ids for different clusters (ex.: 100, 101, 102 for the first cluster, 200,201, 202 for the second one, etc...).

**Motivation:**
I want to run asynchronous replication between two group replication clusters running on k8s under this operator. In order for asynchronous replication to work, all servers should have different server_id value.

**Example manifest:**
```
# cluster: cluster1
---
apiVersion: "mysql.oracle.com/v1"
kind: MySQLCluster
metadata:
  name: mysql-cluster1
spec:
  baseServerId: 100
  replicas: 3

# cluster: cluster2
---
apiVersion: "mysql.oracle.com/v1"
kind: MySQLCluster
metadata:
  name: mysql-cluster2
spec:
  baseServerId: 200
  replicas: 3
 ```
`server_id` flag should be set  based on  value from field `baseServerId`. As a result of applying this manifest operator should create two clusters, first with server ids 100, 101, 102 and second with server id 200, 201, 202.

## Versions

**MySQL Operator Version**: `0.1.0`

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: `Bare metal`
- **OS** (e.g. from /etc/os-release): `Ubuntu 14.04 LTS`
- **Kernel** (e.g. `uname -a`): ` 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- **Others**:

## Anything else we need to know?

If you are open to contributions I would be more then happy to implement this feature.
