### ISSUE TITLE
Create a cluster with a persistent volume failed

### ISSUE THREAD

**Issue by WTwilight** [oracle/mysql-operator#88]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**MySQL Operator Version**:git commit ID:f3b89a4a8fb01a2c8aa13a67a4c7735861fb7dab

**Environment**:
- **Kubernetes version** (use `kubectl version`):v1.9.5
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):CentOS Linux release 7.2.1511 (Core)
- **Kernel** (e.g. `uname -a`):3.10.0-327.el7.x86_64
- **Others**:Docker version:1.12.6

## An error has occurred
When I refer to the tutorial（https://github.com/oracle/mysql-operator/blob/master/docs/user/clusters.md#clusters） to Create a cluster with a persistent volume，An error has occurred：
Error: lstat /tmp/data1: no such file or directory

But,I had create the directory " /tmp/data1" on each k8s worker node.

## Details:
yaml file：
# mysql-cluster-with-volume.yaml 
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-local-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/data1
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mysql-sc

---
apiVersion: "mysql.oracle.com/v1"
kind: MySQLCluster
metadata:
  name: example-mysql-cluster-with-volume
spec:
  replicas: 1
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: mysql-sc
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
```
# kubectl create -f  mysql-cluster-with-volume.yaml

# kubectl get pods
![image](https://user-images.githubusercontent.com/22765072/39359094-254d5bda-4a4b-11e8-9f6c-24872ebae9b6.png)

# kubectl describe pod example-mysql-cluster-with-volume-0
![image](https://user-images.githubusercontent.com/22765072/39359123-4531a23a-4a4b-11e8-933c-e1168f55cb03.png)

# docker logs kubelet
![image](https://user-images.githubusercontent.com/22765072/39359160-655d2f52-4a4b-11e8-9dbc-a200657e7a53.png)
